/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author mathe
 */
public class MenuView extends javax.swing.JFrame {

    /** Creates new form MenuView */
    public MenuView() {
        initComponents();
        this.setTitle("Controle de Patrimonio - FASOFT");
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonEquipamento = new javax.swing.JButton();
        jButtonEstacaoTrabalho = new javax.swing.JButton();
        jButtonLaboratorio = new javax.swing.JButton();
        jButtonLocalizacao = new javax.swing.JButton();
        jLabelCopright = new javax.swing.JLabel();
        jButtonFornecedor = new javax.swing.JButton();
        jLabelImagemDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 520));
        getContentPane().setLayout(null);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(20, 370, 130, 40);

        jButtonEquipamento.setText("Equipamento");
        jButtonEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEquipamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEquipamento);
        jButtonEquipamento.setBounds(20, 120, 130, 40);

        jButtonEstacaoTrabalho.setText("Est. Trabalho");
        jButtonEstacaoTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstacaoTrabalhoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEstacaoTrabalho);
        jButtonEstacaoTrabalho.setBounds(20, 270, 130, 40);

        jButtonLaboratorio.setText("Laboratorio");
        jButtonLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaboratorioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLaboratorio);
        jButtonLaboratorio.setBounds(20, 170, 130, 40);

        jButtonLocalizacao.setText("Localizaçao");
        jButtonLocalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLocalizacao);
        jButtonLocalizacao.setBounds(20, 220, 130, 40);

        jLabelCopright.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelCopright.setText("FASOFT - Faculdade de Engenharia de Software Designed by Matheus ©");
        getContentPane().add(jLabelCopright);
        jLabelCopright.setBounds(220, 450, 360, 10);

        jButtonFornecedor.setText("Fornecedor");
        jButtonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFornecedor);
        jButtonFornecedor.setBounds(20, 70, 130, 40);

        jLabelImagemDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/unirv.jpg"))); // NOI18N
        jLabelImagemDeFundo.setPreferredSize(null);
        getContentPane().add(jLabelImagemDeFundo);
        jLabelImagemDeFundo.setBounds(0, 0, 640, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornecedorActionPerformed
        // TODO add your handling code here:
        new FornecedorView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFornecedorActionPerformed

    private void jButtonLocalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizacaoActionPerformed
        // TODO add your handling code here:
        new LocalizacaoView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLocalizacaoActionPerformed

    private void jButtonEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEquipamentoActionPerformed
        // TODO add your handling code here:
        new EquipamentoView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEquipamentoActionPerformed

    private void jButtonLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaboratorioActionPerformed
        // TODO add your handling code here:
        new LaboratorioView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLaboratorioActionPerformed

    private void jButtonEstacaoTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstacaoTrabalhoActionPerformed
        // TODO add your handling code here:
        new EstacaoTrabalhoView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEstacaoTrabalhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEquipamento;
    private javax.swing.JButton jButtonEstacaoTrabalho;
    private javax.swing.JButton jButtonFornecedor;
    private javax.swing.JButton jButtonLaboratorio;
    private javax.swing.JButton jButtonLocalizacao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelCopright;
    private javax.swing.JLabel jLabelImagemDeFundo;
    // End of variables declaration//GEN-END:variables

}
